= matrix-commander with Docker

NOTE: In the following docker commands, the option `:z` is here to make sure that the commands work in systems that use SELinux (eg. Fedora).
For other systems, this options has no influence and can be ignored or removed.

== Building the image

From the root folder of the git repository, run:

```
docker build -t matrix-commander . -f docker/Dockerfile
```

This will create an image called `matrix-commander`.


== Using the image

This image requires a folder where `matrix-commander` will store data for credentials and end-to-end encryption.
This folder must be provided to further `run` commands using the `/data` mountpoint.

=== Initialization (only do this once)

Run this command to initialize the `matrix-commander` data folder with new credentials − you must answer all the questions that will pop up interactively (homeserver, username, etc.):
```
docker run --rm -ti -v /my/chosen/folder:/data:z matrix-commander
```

You can now use this data folder to send messages or verify your session.


=== Send a message to a room

Given an initialized data folder, run this command to send a message to a room:
```
docker run --rm -v /my/chosen/folder:/data:z matrix-commander -r "<room id>" -m "<some message>"
```

=== Verify the session 

Given an initialized data folder, run this command to start the verification of the matrix-commander session from another existing matrix session:
```
docker run --rm -ti -v /my/chosen/folder:/data:z matrix-commander --verify
```

= matrix-commander with Docker on Raspberry Pi (4b, 32bit, running buster of Raspberry Pi OS)

See Issue #25 for more info:

https://github.com/8go/matrix-commander/issues/25

The libraries
```
libffi-devel libjpeg-devel zlib-devel
```
were added to the 
```
dnf install
```
command.

The command
```
pip3 install wheel && 
```
was added to the
```
pip3 install
```
command.

See commit
https://github.com/8go/matrix-commander/commit/5089d71513685bec6443388dcd105d177191a25e
.
