name: Publish Docker image

env:
  DOCKERHUB_IMAGE: matrix-commander

# on: push
# on: pull_request
# on:
#   push:
#     branches:
#       - master

# Adding "git push origin <tag>" made it trigger the workflow twice.
# Hence made it so that only pushing tags triggers the workflow.
# And only if the tag is a version ending in ".0". 
# Minor versions like "v2.40.1" will be skipped.
on:
  push:
    tags:
      - 'v.*\.0'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"

      # Required if building multi-arch images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}:latest, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}:${{ steps.getversion.outputs.version }}
