name: PyPI Publish

# Adding "git push origin <tag>" made it trigger the workflow twice.
# Hence made it so that only pushing tags triggers the workflow.
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  publish-pypi:
    # Only publish on `main` branch
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:  # Don't forget permissions
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@release/v7

      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
