name: Run tests from tests directory

on:
  # # every single push seems to much overhead, hence commented out
  # push:
  #   branches: [ "master", "*" ]
  # # dependabot PRs fail because they seem to have no access to secrets, hence commented out.
  # pull_request:
  #  branches: [ "master" ]
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  python-version: "3.*" 

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"

      - name: Install system dependencies
        run:  sudo apt install libdbus-1-dev libolm-dev

      - name: Upgrade PIP
        run:  python -m pip install --upgrade pip

      - name: Install requirements for Matrix Commander
        run:  pip install -r requirements.txt

      - name: Source install of Matrix Commander
        run:  pip install .

      - name: Python version
        run:  python --version

      - name: ls
        run:  ls

      - name: ls matrix_commander
        run:  ls matrix_commander

      - name: Test version
        run:  ./tests/test-version.sh
        
      - name: Log in to matrix server
        env:
          MATRIX_HOMESERVER: ${{ secrets.MATRIX_HOMESERVER }}
          MATRIX_HOMESERVER_DOMAIN: ${{ secrets.MATRIX_HOMESERVER_DOMAIN }}
          MATRIX_ROOM: ${{ secrets.MATRIX_ROOM }}
          MATRIX_USERNAME: ${{ secrets.MATRIX_USERNAME }}
          MATRIX_PASSWORD: ${{ secrets.MATRIX_PASSWORD }}
        run: matrix-commander --login password --user-login "${MATRIX_USERNAME}" --password "${MATRIX_PASSWORD}" --homeserver "${MATRIX_HOMESERVER}" --device "ci" --room-default "${MATRIX_ROOM}" -m "matrix-commander posted from CI (${GITHUB_REPOSITORY} / ${GITHUB_REF})"

      - name: Test events
        run:  ./tests/test-event.sh

      - name: Test delete event
        run:  ./tests/test-delete.sh

      - name: Test REST
        run:  ./tests/test-rest.sh

      - name: Test set/get
        run:  ./tests/test-setget.sh

      - name: Test send
        run:  python ./tests/test-send.py

      - name: Test upload
        run:  ./tests/test-upload.sh

      - name: Log out of matrix server
        run:  matrix-commander -m "matrix-commander CI log out" --logout me
