# This is a basic workflow to perform automated tests with Actions

name: Run DELETE test from tests directory manually

on:
  workflow_dispatch:

env:
  python-version: ""
  test-case: "test-delete.sh"
  MC_OPTIONS: " --verbose "

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install system dependencies
        run:  sudo apt install libdbus-1-dev libolm-dev

      - name: Upgrade PIP
        run:  python -m pip install --upgrade pip

      - name: Install requirements for Matrix Commander
        run:  pip install -r requirements.txt

      - name: Source install of Matrix Commander
        run:  pip install .

      - name: Python version
        run:  python --version

      - name: ls
        run:  ls

      - name: ls matrix_commander
        run:  ls matrix_commander

      - name: Log in to matrix server
        env:
          MATRIX_HOMESERVER: ${{ secrets.MATRIX_HOMESERVER }}
          MATRIX_HOMESERVER_DOMAIN: ${{ secrets.MATRIX_HOMESERVER_DOMAIN }}
          MATRIX_ROOM: ${{ secrets.MATRIX_ROOM }}
          MATRIX_USERNAME: ${{ secrets.MATRIX_USERNAME }}
          MATRIX_PASSWORD: ${{ secrets.MATRIX_PASSWORD }}
        run: matrix-commander --login password --user-login "${MATRIX_USERNAME}" --password "${MATRIX_PASSWORD}" --homeserver "${MATRIX_HOMESERVER}" --device "ci" --room-default "${MATRIX_ROOM}" -m "matrix-commander posted from CI (${GITHUB_REPOSITORY} / ${GITHUB_REF})"

      - name: Test ${{ env.test-case }}
        run:  ./tests/${{ env.test-case }}

      - name: Log out of matrix server
        run:  matrix-commander -m "matrix-commander CI log out" --logout me
